version: "3"

services:
  urlshortify:
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - urlshortify-network
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - mongodb

  redis:
    image: redis
    networks:
      - urlshortify-network
    ports:
      - 6379:6379

  mongodb:
    image: mongo:3.6
    networks:
      - urlshortify-network
    ports:
      - 27017:27017
    environment:
      - MONGO-INITDB-DABASE=url-shortener

networks:
  urlshortify-network:


